[package]
name = "Pyth"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[addresses]
pyth = "_"

[dev-addresses]
pyth = "0x182"
